apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-flask
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-flask
  template:
    metadata:
      labels:
        app: backend-flask
    spec:
      nodeName: controlplane
      containers:
        - name: backend-flask
          image: localhost:5000/backend-flask:latest 
          ports:
            - containerPort: 6000

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
  type: ClusterIP  